/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDelegationManager } from "./IDelegationManager";
export type { IRewardBoosterNFT } from "./IRewardBoosterNFT";
export type { NFTLiquidityPool } from "./NFTLiquidityPool";
