/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDelegationManager,
  IDelegationManagerInterface,
} from "../../../contracts/NFTLiquidityPool.sol/IDelegationManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "validatorAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "delegatorAmount",
        type: "uint256",
      },
    ],
    name: "depositRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDelegationManager__factory {
  static readonly abi = _abi;
  static createInterface(): IDelegationManagerInterface {
    return new Interface(_abi) as IDelegationManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDelegationManager {
    return new Contract(address, _abi, runner) as unknown as IDelegationManager;
  }
}
