/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardBoosterNFT,
  IRewardBoosterNFTInterface,
} from "../../../contracts/NFTLiquidityPool.sol/IRewardBoosterNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "boostBips",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRewardBoosterNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardBoosterNFTInterface {
    return new Interface(_abi) as IRewardBoosterNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRewardBoosterNFT {
    return new Contract(address, _abi, runner) as unknown as IRewardBoosterNFT;
  }
}
